---
users:
  - default
  - name: ubuntu
    gecos: Ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin, docker
    shell: /bin/bash
    ssh_import_id: None
    lock_passwd: false
    passwd: $6$rounds=4096$iZ8ODZ/7G9HmUtza$b6v0K347LXlW1tpIUWH47kUM9PUG8wQWNdhpETL446CNHaHloEcLo.1iJreVscrSa8AJiyWD7ZX1/jcpB9dWo.

#cloud-config
package_update: true
package_upgrade: true

write_files:
- encoding: b64
  owner: ubuntu:ubuntu
  path: /tmp/install.sh
  permissions: '0551'
  content: |
    IyEvYmluL2Jhc2gKIyMjIyMjIyMjIyMjIyMjIyMgTEZEMjU5OjIwMjItMTEtMjMgc18wMi9rOHNX
    b3JrZXIuc2ggIyMjIyMjIyMjIyMjIyMjIwojIFRoZSBjb2RlIGhlcmVpbiBpczogQ29weXJpZ2h0
    IHRoZSBMaW51eCBGb3VuZGF0aW9uLCAyMDIyCiMKIyBUaGlzIENvcHlyaWdodCBpcyByZXRhaW5l
    ZCBmb3IgdGhlIHB1cnBvc2Ugb2YgcHJvdGVjdGluZyBmcmVlCiMgcmVkaXN0cmlidXRpb24gb2Yg
    c291cmNlLgojCiMgICAgIFVSTDogICAgaHR0cHM6Ly90cmFpbmluZy5saW51eGZvdW5kYXRpb24u
    b3JnCiMgICAgIGVtYWlsOiAgaW5mb0BsaW51eGZvdW5kYXRpb24ub3JnCiMKIyBUaGlzIGNvZGUg
    aXMgZGlzdHJpYnV0ZWQgdW5kZXIgVmVyc2lvbiAyIG9mIHRoZSBHTlUgR2VuZXJhbCBQdWJsaWMK
    IyBMaWNlbnNlLCB3aGljaCB5b3Ugc2hvdWxkIGhhdmUgcmVjZWl2ZWQgd2l0aCB0aGUgc291cmNl
    LgojVmVyc2lvbiAxLjI1LjEKIwojIFRoaXMgc2NyaXB0IGlzIGludGVuZGVkIHRvIGJlIHJ1biBv
    biBhbiBVYnVudHUgMjAuMDQsIAojIDJjcHUsIDhHLgojIEJ5IFRpbSBTZXJld2ljeiwgMTAvMjAy
    MiBHUEwKCiMgTm90ZSB0aGVyZSBpcyBhIGxvdCBvZiBzb2Z0d2FyZSBkb3dubG9hZGVkLCB3aGlj
    aCBtYXkgcmVxdWlyZQojIHNvbWUgdHJvdWJsZXNob290aW5nIGlmIGFueSBvZiB0aGUgc2l0ZXMg
    dXBkYXRlcyB0aGVpciBjb2RlLAojIHdoaWNoIHNob3VsZCBiZSBleHBlY3RlZAoKCiMgQ2hlY2sg
    dG8gc2VlIGlmIHRoZSBzY3JpcHQgaGFzIGJlZW4gcnVuIGJlZm9yZS4gRXhpdCBvdXQgaWYgc28u
    CkZJTEU9L2s4c2NwX3J1bgppZiBbIC1mICIkRklMRSIgXTsgdGhlbgogICAgZWNobyAiV0FSTklO
    RyEiCiAgICBlY2hvICIkRklMRSBleGlzdHMuIFNjcmlwdCBoYXMgYWxyZWFkeSBiZWVuLiBEbyBu
    b3QgcnVuIG9uIGNvbnRyb2wgcGxhbmUuIgogICAgZWNobyAiVGhpcyBzaG91bGQgYmUgcnVuIG9u
    IHRoZSB3b3JrZXIgbm9kZS4iCiAgICBlY2hvCiAgICBleGl0IDEKZWxzZSAKICAgIGVjaG8gIiRG
    SUxFIGRvZXMgbm90IGV4aXN0LiBSdW5uaW5nICBzY3JpcHQiCmZpCgoKIyBDcmVhdGUgYSBmaWxl
    IHdoZW4gdGhpcyBzY3JpcHQgaXMgc3RhcnRlZCB0byBrZWVwIGl0IGZyb20gcnVubmluZyAKIyBv
    biB0aGUgY29udHJvbCBwbGFuZSBub2RlLgpzdWRvIHRvdWNoIC9rOHNjcF9ydW4KCiMgVXBkYXRl
    IHRoZSBzeXN0ZW0Kc3VkbyBhcHQgdXBkYXRlIDsgc3VkbyBhcHQgdXBncmFkZSAteQoKIyBJbnN0
    YWxsIG5lY2Vzc2FyeSBzb2Z0d2FyZQpzdWRvIGFwdCBpbnN0YWxsIGN1cmwgYXB0LXRyYW5zcG9y
    dC1odHRwcyB2aW0gZ2l0IHdnZXQgZ251cGcyIHNvZnR3YXJlLXByb3BlcnRpZXMtY29tbW9uIGFw
    dC10cmFuc3BvcnQtaHR0cHMgY2EtY2VydGlmaWNhdGVzIC15CgojIEFkZCByZXBvIGZvciBLdWJl
    cm5ldGVzCmN1cmwgLXMgaHR0cHM6Ly9wYWNrYWdlcy5jbG91ZC5nb29nbGUuY29tL2FwdC9kb2Mv
    YXB0LWtleS5ncGcgfCBzdWRvIGFwdC1rZXkgYWRkIC0KZWNobyAiZGViIGh0dHBzOi8vYXB0Lmt1
    YmVybmV0ZXMuaW8vIGt1YmVybmV0ZXMteGVuaWFsIG1haW4iIHwgc3VkbyB0ZWUgL2V0Yy9hcHQv
    c291cmNlcy5saXN0LmQva3ViZXJuZXRlcy5saXN0CgojIEluc3RhbGwgdGhlIEt1YmVybmV0ZXMg
    c29mdHdhcmUsIGFuZCBsb2NrIHRoZSB2ZXJzaW9uIApzdWRvIGFwdCB1cGRhdGUKc3VkbyBhcHQg
    LXkgaW5zdGFsbCBrdWJlbGV0PTEuMjUuNS0wMCBrdWJlYWRtPTEuMjUuNS0wMCBrdWJlY3RsPTEu
    MjUuNS0wMApzdWRvIGFwdC1tYXJrIGhvbGQga3ViZWxldCBrdWJlYWRtIGt1YmVjdGwKCiMgRW5z
    dXJlIEt1YmVsZXQgaXMgcnVubmluZwpzdWRvIHN5c3RlbWN0bCBlbmFibGUgLS1ub3cga3ViZWxl
    dAoKIyBEaXNhYmxlIHN3YXAganVzdCBpbiBjYXNlIApzdWRvIHN3YXBvZmYgLWEKCiMgRW5zdXJl
    IEtlcm5lbCBoYXMgbW9kdWxlcwpzdWRvIG1vZHByb2JlIG92ZXJsYXkKc3VkbyBtb2Rwcm9iZSBi
    cl9uZXRmaWx0ZXIKCiMgVXBkYXRlIG5ldHdvcmtpbmcgdG8gYWxsb3cgdHJhZmZpYwpjYXQgPDxF
    T0YgfCBzdWRvIHRlZSAvZXRjL3N5c2N0bC5kL2t1YmVybmV0ZXMuY29uZgpuZXQuYnJpZGdlLmJy
    aWRnZS1uZi1jYWxsLWlwNnRhYmxlcyA9IDEKbmV0LmJyaWRnZS5icmlkZ2UtbmYtY2FsbC1pcHRh
    YmxlcyA9IDEKbmV0LmlwdjQuaXBfZm9yd2FyZCA9IDEKRU9GCgpzdWRvIHN5c2N0bCAtLXN5c3Rl
    bQoKIyBDb25maWd1cmUgY29udGFpbmVyZCBzZXR0aW5ncwpjYXQgPDxFT0YgfCBzdWRvIHRlZSAv
    ZXRjL21vZHVsZXMtbG9hZC5kL2NvbnRhaW5lcmQuY29uZiAKb3ZlcmxheQpicl9uZXRmaWx0ZXIK
    RU9GCgpzdWRvIHN5c2N0bCAtLXN5c3RlbQoKIyBJbnN0YWxsIHRoZSBjb250YWluZXJkIHNvZnR3
    YXJlCmN1cmwgLWZzU0wgaHR0cHM6Ly9kb3dubG9hZC5kb2NrZXIuY29tL2xpbnV4L3VidW50dS9n
    cGcgfCBzdWRvIGFwdC1rZXkgYWRkIC0Kc3VkbyBhZGQtYXB0LXJlcG9zaXRvcnkgImRlYiBbYXJj
    aD1hbWQ2NF0gaHR0cHM6Ly9kb3dubG9hZC5kb2NrZXIuY29tL2xpbnV4L3VidW50dSAkKGxzYl9y
    ZWxlYXNlIC1jcykgc3RhYmxlIgpzdWRvIGFwdCB1cGRhdGUKc3VkbyBhcHQgaW5zdGFsbCBjb250
    YWluZXJkLmlvIC15CgojIENvbmZpZ3VyZSBjb250YWluZXJkIGFuZCByZXN0YXJ0CnN1ZG8gbWtk
    aXIgLXAgL2V0Yy9jb250YWluZXJkCmNvbnRhaW5lcmQgY29uZmlnIGRlZmF1bHQgfCBzdWRvIHRl
    ZSAvZXRjL2NvbnRhaW5lcmQvY29uZmlnLnRvbWwKc3VkbyBzeXN0ZW1jdGwgcmVzdGFydCBjb250
    YWluZXJkCnN1ZG8gc3lzdGVtY3RsIGVuYWJsZSBjb250YWluZXJkCgojICBDcmVhdGUgdGhlIGNv
    bmZpZyBmaWxlIHNvIG5vIG1vcmUgZXJyb3JzCiMgSW5zdGFsbCBhbmQgY29uZmlndXJlIGNyaWN0
    bApleHBvcnQgVkVSPSJ2MS4yNS4wIgoKd2dldCBodHRwczovL2dpdGh1Yi5jb20va3ViZXJuZXRl
    cy1zaWdzL2NyaS10b29scy9yZWxlYXNlcy9kb3dubG9hZC8kVkVSL2NyaWN0bC0kVkVSLWxpbnV4
    LWFtZDY0LnRhci5negoKdGFyIHp4dmYgY3JpY3RsLSRWRVItbGludXgtYW1kNjQudGFyLmd6Cgpz
    dWRvIG12IGNyaWN0bCAvdXNyL2xvY2FsL2JpbgoKIyBTZXQgdGhlIGVuZHBvaW50cyB0byBhdm9p
    ZCB0aGUgZGVwcmVjYXRpb24gZXJyb3IKc3VkbyBjcmljdGwgY29uZmlnIC0tc2V0IFwKcnVudGlt
    ZS1lbmRwb2ludD11bml4Oi8vL3J1bi9jb250YWluZXJkL2NvbnRhaW5lcmQuc29jayBcCi0tc2V0
    IGltYWdlLWVuZHBvaW50PXVuaXg6Ly8vcnVuL2NvbnRhaW5lcmQvY29udGFpbmVyZC5zb2NrCgoj
    IEFkZCBIZWxtIHRvIG1ha2Ugb3VyIGxpZmUgZWFzaWVyCndnZXQgaHR0cHM6Ly9nZXQuaGVsbS5z
    aC9oZWxtLXYzLjkuMC1saW51eC1hbWQ2NC50YXIuZ3oKdGFyIC14ZiBoZWxtLXYzLjkuMC1saW51
    eC1hbWQ2NC50YXIuZ3oKc3VkbyBjcCBsaW51eC1hbWQ2NC9oZWxtIC91c3IvbG9jYWwvYmluLwoK
    IyBVc2UgQ2lsaXVtIGFzIHRoZSBuZXR3b3JrIHBsdWdpbgojIEluc3RhbGwgdGhlIENMSSBmaXJz
    dApleHBvcnQgQ0lMSVVNX0NMSV9WRVJTSU9OPSQoY3VybCAtcyBodHRwczovL3Jhdy5naXRodWJ1
    c2VyY29udGVudC5jb20vY2lsaXVtL2NpbGl1bS1jbGkvbWFzdGVyL3N0YWJsZS50eHQpCmV4cG9y
    dCBDTElfQVJDSD1hbWQ2NAoKIyBFbnN1cmUgY29ycmVjdCBhcmNoaXRlY3R1cmUKaWYgWyAiJCh1
    bmFtZSAtbSkiID0gImFhcmNoNjQiIF07IHRoZW4gQ0xJX0FSQ0g9YXJtNjQ7IGZpCmN1cmwgLUwg
    LS1mYWlsIC0tcmVtb3RlLW5hbWUtYWxsIGh0dHBzOi8vZ2l0aHViLmNvbS9jaWxpdW0vY2lsaXVt
    LWNsaS9yZWxlYXNlcy9kb3dubG9hZC8ke0NJTElVTV9DTElfVkVSU0lPTn0vY2lsaXVtLWxpbnV4
    LSR7Q0xJX0FSQ0h9LnRhci5nenssLnNoYTI1NnN1bX0KCiMgTWFrZSBzdXJlIGRvd25sb2FkIHdv
    cmtlZApzaGEyNTZzdW0gLS1jaGVjayBjaWxpdW0tbGludXgtJHtDTElfQVJDSH0udGFyLmd6LnNo
    YTI1NnN1bQoKIyBNb3ZlIGJpbmFyeSB0byBjb3JyZWN0IGxvY2F0aW9uIGFuZCByZW1vdmUgdGFy
    YmFsbApzdWRvIHRhciB4enZmQyBjaWxpdW0tbGludXgtJHtDTElfQVJDSH0udGFyLmd6IC91c3Iv
    bG9jYWwvYmluCnJtIGNpbGl1bS1saW51eC0ke0NMSV9BUkNIfS50YXIuZ3p7LC5zaGEyNTZzdW19
    CgoKIyAtLS0tLS0tLS0tLS0gRE8gVEhJUyBPTiBUSEUgRklSU1QgQ1RSTCBOT0RFIC0tLS0tLS0t
    LS0tLS0tLQojIHN1ZG8ga3ViZWFkbSBpbml0IC0tcG9kLW5ldHdvcmstY2lkciAxMC4yMDAuMC4w
    LzE2IC0tdXBsb2FkLWNlcnRzIC0tY29udHJvbC1wbGFuZS1lbmRwb2ludCAzNS4yMDkuMTYxLjEz
    NwojIGNpbGl1bSBpbnN0YWxsCgojIFJlYWR5IHRvIGNvbnRpbnVlCnNsZWVwIDMKZWNobwplY2hv
    CmVjaG8gJyoqKioqKioqKioqKioqKioqKioqKioqKioqKicKZWNobwplY2hvICJDb250aW51ZSB0
    byB0aGUgbmV4dCBzdGVwIgplY2hvCmVjaG8gIlVzZSBzdWRvIGFuZCBjb3B5IG92ZXIga3ViZWFk
    bSBqb2luIGNvbW1hbmQgZnJvbSIKZWNobyAiY29udHJvbCBwbGFuZS4iCmVjaG8KZWNobyAnKioq
    KioqKioqKioqKioqKioqKioqKioqKioqJwplY2hvCmVjaG8KCg==


runcmd:
 - [ sudo, /tmp/install.sh ]
